# POTLS-DB | Empty Fruit Bunch Soda — Sensitivity LOW
# Archetype: SG-rico | Linkage bounds: low
project:
  name: EFB_SD_low
  dataset_id: POTLS_EFB_SD_L
  biomass_source: Empty_Fruit_Bunch
  pulping_method: Soda
  parameter_set: sensitivity_low
  archetype: SG-rico
monomers:
  G: 0.4
  S: 0.6
  H: 0.0
linkages:
  beta-O-4: 0.872
  beta-beta: 0.051
  beta-5: 0.051
  5-5: 0.0
  4-O-5: 0.026
  DBDO: 0.0
degree_of_polymerization:
  min: 10
  max: 16
  M0_gmol: 198.2
