# POTLS-DB | Empty Fruit Bunch Organosolv — Sensitivity LOW
# Archetype: SG-intermedio | Linkage bounds: low
project:
  name: EFB_OR_low
  dataset_id: POTLS_EFB_OR_L
  biomass_source: Empty_Fruit_Bunch
  pulping_method: Organosolv
  parameter_set: sensitivity_low
  archetype: SG-intermedio
monomers:
  G: 0.714
  S: 0.286
  H: 0.0
linkages:
  beta-O-4: 0.822
  beta-beta: 0.038
  beta-5: 0.089
  5-5: 0.013
  4-O-5: 0.038
  DBDO: 0.0
degree_of_polymerization:
  min: 3
  max: 8
  M0_gmol: 188.8
