# POTLS-DB | Mesocarp Fiber Organosolv — Sensitivity LOW
# Archetype: G-dominante | Linkage bounds: low
project:
  name: MF_OR_low
  dataset_id: POTLS_MF_OR_L
  biomass_source: Mesocarp_Fiber
  pulping_method: Organosolv
  parameter_set: sensitivity_low
  archetype: G-dominante
monomers:
  G: 0.833
  S: 0.167
  H: 0.0
linkages:
  beta-O-4: 0.746
  beta-beta: 0.038
  beta-5: 0.127
  5-5: 0.038
  4-O-5: 0.038
  DBDO: 0.013
degree_of_polymerization:
  min: 3
  max: 8
  M0_gmol: 185.2
