# POTLS-DB | Empty Fruit Bunch Kraft — Sensitivity HIGH
# Archetype: SG-rico | Linkage bounds: high
project:
  name: EFB_KR_high
  dataset_id: POTLS_EFB_KR_H
  biomass_source: Empty_Fruit_Bunch
  pulping_method: Kraft
  parameter_set: sensitivity_high
  archetype: SG-rico
monomers:
  G: 0.303
  S: 0.697
  H: 0.0
linkages:
  beta-O-4: 0.642
  beta-beta: 0.154
  beta-5: 0.098
  5-5: 0.033
  4-O-5: 0.065
  DBDO: 0.008
degree_of_polymerization:
  min: 10
  max: 16
  M0_gmol: 201.3
