# POTLS-DB | Kernel Shell Kraft — Sensitivity HIGH
# Archetype: G-dominante | Linkage bounds: high
project:
  name: KS_KR_high
  dataset_id: POTLS_KS_KR_H
  biomass_source: Kernel_Shell
  pulping_method: Kraft
  parameter_set: sensitivity_high
  archetype: G-dominante
monomers:
  G: 0.909
  S: 0.091
  H: 0.0
linkages:
  beta-O-4: 0.561
  beta-beta: 0.065
  beta-5: 0.138
  5-5: 0.106
  4-O-5: 0.081
  DBDO: 0.049
degree_of_polymerization:
  min: 11
  max: 18
  M0_gmol: 182.9
