# POTLS-DB | Mesocarp Fiber Kraft — Sensitivity HIGH
# Archetype: SG-intermedio | Linkage bounds: high
project:
  name: MF_KR_high
  dataset_id: POTLS_MF_KR_H
  biomass_source: Mesocarp_Fiber
  pulping_method: Kraft
  parameter_set: sensitivity_high
  archetype: SG-intermedio
monomers:
  G: 0.588
  S: 0.412
  H: 0.0
linkages:
  beta-O-4: 0.635
  beta-beta: 0.124
  beta-5: 0.116
  5-5: 0.05
  4-O-5: 0.058
  DBDO: 0.017
degree_of_polymerization:
  min: 10
  max: 17
  M0_gmol: 192.4
