# POTLS-DB | Mesocarp Fiber Soda — Sensitivity HIGH
# Archetype: G-dominante | Linkage bounds: high
project:
  name: MF_SD_high
  dataset_id: POTLS_MF_SD_H
  biomass_source: Mesocarp_Fiber
  pulping_method: Soda
  parameter_set: sensitivity_high
  archetype: G-dominante
monomers:
  G: 1.0
  S: 0.0
  H: 0.0
linkages:
  beta-O-4: 0.561
  beta-beta: 0.065
  beta-5: 0.138
  5-5: 0.106
  4-O-5: 0.081
  DBDO: 0.049
degree_of_polymerization:
  min: 11
  max: 17
  M0_gmol: 180.2
